name: Release

on:
  release:
    types:
      - created

jobs:

  ubuntu-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libhiredis-dev
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Debug
    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build
    - name: Packing
      run: |
        cpack --config build/CPackConfig.cmake
    - name: Upload asset
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/package/*.tar.gz
        overwrite: true

  macos-release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing dependencies
      run: |
        git clone https://github.com/redis/hiredis.git
        cd hiredis
        make
        sudo make install
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Debug
    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build
    - name: Packing
      run: |
        cpack --config build/CPackConfig.cmake
    - name: Upload asset
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/package/*.tar.gz
        overwrite: true

  windows-release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing dependencies
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        bootstrap-vcpkg.bat
        vcpkg integrate install
        vcpkg install hiredis:x64-windows
    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build
    - name: Packing
      run: |
        cpack --config build/CPackConfig.cmake
    - name: Upload asset
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/package/*.tar.gz
        overwrite: true
